# Generated by Django 4.0.6 on 2022-08-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('habitad', models.CharField(max_length=20)),
                ('esperanza_vida', models.IntegerField()),
                ('puede_volar', models.BooleanField()),
            ],
        ),
    ]
